server:
  port: 8761

eureka:
  instance:
    net: host
    preferIpAddress: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
          defaultZone: http://120.24.36.69:${server.port}/eureka/